/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "on-primary-fixed": "#274635",
          "primary-container": "#c7ebd4",
          "tertiary-dim": "#4e5736",
          "on-error": "#fff7f6",
          "inverse-surface": "#0c0f0e",
          "secondary-fixed-dim": "#d3d5d1",
          "error-dim": "#4e0309",
          "surface-bright": "#f9f9f8",
          "on-tertiary-fixed": "#404828",
          "tertiary-fixed": "#e7f0c4",
          "on-secondary-fixed-variant": "#595c59",
          "tertiary-fixed-dim": "#d8e1b7",
          "inverse-primary": "#d8fce4",
          "tertiary-container": "#e7f0c4",
          "secondary": "#5d605d",
          "primary-dim": "#3a5947",
          "on-tertiary-fixed-variant": "#5c6442",
          "surface-dim": "#d2dcdb",
          "on-surface": "#2c3433",
          "on-secondary": "#f8f9f5",
          "surface-tint": "#466553",
          "background": "#f9f9f8",
          "secondary-fixed": "#e1e3df",
          "outline": "#747c7c",
          "error": "#9f403d",
          "surface-container": "#eaefee",
          "on-primary-container": "#395847",
          "secondary-container": "#e1e3df",
          "surface-container-low": "#f1f4f3",
          "error-container": "#fe8983",
          "on-secondary-container": "#4f524f",
          "on-background": "#2c3433",
          "on-surface-variant": "#586160",
          "secondary-dim": "#515451",
          "primary-fixed": "#c7ebd4",
          "inverse-on-surface": "#9b9d9d",
          "on-tertiary-container": "#525a39",
          "on-error-container": "#752121",
          "surface-container-highest": "#dce4e3",
          "surface-container-high": "#e3e9e8",
          "primary-fixed-dim": "#baddc6",
          "primary": "#466553",
          "tertiary": "#5a6341",
          "on-secondary-fixed": "#3d403d",
          "outline-variant": "#abb4b3",
          "on-primary": "#e1ffea",
          "on-tertiary": "#f4fed1",
          "surface-variant": "#dce4e3",
          "surface-container-lowest": "#ffffff",
          "surface": "#f9f9f8",
          "on-primary-fixed-variant": "#436250"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "fontFamily": {
          "headline": ["Public Sans"],
          "body": ["Public Sans"],
          "label": ["Public Sans"]
      }
    },
  },
  plugins: [],
}
