server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/menus/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/slots/**

        - id: pricing-service
          uri: lb://pricing-service
          predicates:
            - Path=/api/pricing/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
